import io
import re
from youtube_transcript_api import YouTubeTranscriptApi
from langchain_ollama import OllamaLLM
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime

llm = OllamaLLM(model="llama3.2")

def extract_video_id(url: str) -> str:
    """Extract YouTube video ID from URL."""
    patterns = [
        r"(?:v=|\/)([0-9A-Za-z_-]{11}).*",
        r"(?:youtu\.be\/)([0-9A-Za-z_-]{11})",
        r"(?:embed\/)([0-9A-Za-z_-]{11})",
    ]
    for pattern in patterns:
        match = re.search(pattern, url)
        if match:
            return match.group(1)
    raise ValueError("Invalid YouTube URL. Please check and try again.")

def get_transcript(video_id: str) -> str:
    """Get transcript from YouTube video."""
    try:
        ytt_api = YouTubeTranscriptApi()
        transcript_list = ytt_api.fetch(video_id)
        full_text = " ".join([t.text for t in transcript_list])
        return full_text
    except Exception as e:
        raise ValueError(f"Could not get transcript: {str(e)}. Make sure the video has captions enabled.")

def generate_notes(transcript: str, video_url: str) -> dict:
    """Generate structured study notes from transcript."""

    # Truncate transcript if too long
    max_chars = 4000
    if len(transcript) > max_chars:
        transcript_sample = transcript[:max_chars] + "..."
    else:
        transcript_sample = transcript

    # Generate comprehensive notes
    notes_prompt = f"""You are an expert academic note-taker. Create comprehensive study notes from this video transcript.

VIDEO TRANSCRIPT:
{transcript_sample}

Generate DETAILED study notes with these EXACT sections:

## 📚 TOPIC OVERVIEW
Write 3-4 sentences summarizing what this video is about.

## 🎯 KEY CONCEPTS
List 8-10 key concepts explained in the video. For each:
- **Concept Name**: Brief explanation (1-2 sentences)

## 📝 DETAILED NOTES
Write detailed notes organized by topic. Cover all major points discussed.
Use bullet points and sub-bullets for clarity.

## 💡 IMPORTANT DEFINITIONS
List 5-8 important terms/definitions from the video.

## ⚡ QUICK REVISION POINTS
List 10 quick bullet points for fast revision.

## ❓ IMPORTANT QUESTIONS & ANSWERS
Generate 15 important questions with detailed answers based on the content.
Format: Q1: [question] A1: [answer]

## 🔑 KEY TAKEAWAYS
List 5 main takeaways from this video.

Be thorough, educational, and well-organized."""

    notes = llm.invoke(notes_prompt)
    return {"notes": notes, "transcript_length": len(transcript)}

def create_pdf(notes_content: str, video_url: str, username: str) -> bytes:
    """Create a premium PDF from study notes."""

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=letter,
        rightMargin=0.75*inch, leftMargin=0.75*inch,
        topMargin=0.75*inch, bottomMargin=0.75*inch
    )

    styles = getSampleStyleSheet()
    story = []

    # Custom styles
    title_style = ParagraphStyle("Title",
        fontSize=24, textColor=colors.HexColor("#3B82F6"),
        alignment=TA_CENTER, spaceAfter=6, fontName="Helvetica-Bold")

    subtitle_style = ParagraphStyle("Subtitle",
        fontSize=11, textColor=colors.HexColor("#6B7280"),
        alignment=TA_CENTER, spaceAfter=4)

    heading_style = ParagraphStyle("Heading",
        fontSize=14, textColor=colors.HexColor("#1e3a5f"),
        spaceBefore=16, spaceAfter=8, fontName="Helvetica-Bold",
        borderPad=6,)

    body_style = ParagraphStyle("Body",
        fontSize=10, textColor=colors.HexColor("#374151"),
        spaceAfter=4, leading=16, alignment=TA_LEFT)

    qa_q_style = ParagraphStyle("QQ",
        fontSize=10, textColor=colors.HexColor("#1e3a5f"),
        spaceAfter=2, leading=14, fontName="Helvetica-Bold")

    qa_a_style = ParagraphStyle("QA",
        fontSize=10, textColor=colors.HexColor("#374151"),
        spaceAfter=8, leading=14)

    # Header
    story.append(Paragraph("🎥 GenBI Study Notes", title_style))
    story.append(Paragraph("AI-Generated from YouTube", subtitle_style))
    story.append(Paragraph(f"Generated by: {username} | {datetime.now().strftime('%B %d, %Y')}", subtitle_style))
    story.append(Paragraph(f"Source: {video_url[:80]}{'...' if len(video_url) > 80 else ''}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#3B82F6"), spaceAfter=16))
    story.append(Spacer(1, 8))

    # Process notes content
    lines = notes_content.split("\n")
    in_qa = False

    for line in lines:
        line = line.strip()
        if not line:
            story.append(Spacer(1, 4))
            continue

        # Section headings
        if line.startswith("## "):
            heading_text = line.replace("## ", "").strip()
            story.append(HRFlowable(width="100%", thickness=0.5,
                color=colors.HexColor("#e5e7eb"), spaceBefore=8, spaceAfter=4))
            story.append(Paragraph(heading_text, heading_style))
            in_qa = "QUESTION" in heading_text.upper() or "Q&A" in heading_text.upper()

        # Q&A formatting
        elif in_qa and line.startswith("Q") and ":" in line[:5]:
            try:
                story.append(Paragraph(f"🔵 {line}", qa_q_style))
            except:
                story.append(Paragraph(line, qa_q_style))

        elif in_qa and line.startswith("A") and ":" in line[:5]:
            try:
                story.append(Paragraph(f"   {line}", qa_a_style))
            except:
                story.append(Paragraph(line, qa_a_style))

        # Bold text **text**
        elif "**" in line:
            line = line.replace("**", "<b>", 1).replace("**", "</b>", 1)
            try:
                story.append(Paragraph(line, body_style))
            except:
                story.append(Paragraph(line.replace("<b>", "").replace("</b>", ""), body_style))

        # Bullet points
        elif line.startswith("- ") or line.startswith("• "):
            text = line[2:].strip()
            try:
                story.append(Paragraph(f"• {text}", body_style))
            except:
                story.append(Paragraph(f"• {text}", body_style))

        # Regular text
        else:
            try:
                story.append(Paragraph(line, body_style))
            except:
                pass

    # Footer
    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#3B82F6")))
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        "Generated by GenBI AI — YouTube Study Notes Generator | Confidential",
        subtitle_style
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()

def generate_youtube_notes(video_url: str, username: str) -> bytes:
    """Main function — extract transcript, generate notes, create PDF."""
    video_id = extract_video_id(video_url)
    transcript = get_transcript(video_id)
    notes_data = generate_notes(transcript, video_url)
    pdf_bytes = create_pdf(notes_data["notes"], video_url, username)
    return pdf_bytes, notes_data["notes"]